env:
  global:
    - GCS_BUCKET=autobuilds.grr-response.com
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - APPVEYOR_ACCOUNT_NAME=grr
    - APPVEYOR_WINDOWS_TEMPLATES_SLUG=grr-5wmt5
    - APPVEYOR_E2E_TESTS_SLUG=grr
    - APPVEYOR_DOCKER_BUILD_SLUG=grr-iqgqm
    - SERVICE_FILE_ENCRYPTION_KEY_VAR="encrypted_38884bbe6880_key"
    - SERVICE_FILE_ENCRYPTION_IV_VAR="encrypted_38884bbe6880_iv"
    - secure: "ZE2WGDHnMX3QcLS9XNjgaC0q+Vy9mjDGdvkKd+IExUdRe8bcPNe0sLxL7G5FnkbBZQTydUpD/EDgT9dCAbBH22PfgO/J4KfM445NYVNWC3tTeZ6L2jYuVfu3xnGp6GyBGIrj8zLb1Mv1AhQL1vRwo8dsCDptY7bWH4sFnZlocDo="

matrix:
  include:
    # 64-bit deb builds
    - os: linux
      dist: xenial
      language: python
      python: 2.7
      addons:
        apt:
          packages:
            - fakeroot
            - debhelper
            - libffi-dev
            - libssl-dev
            - python-dev
        chrome: stable
      env:
        - GCS_TAG=ubuntu_64bit
      before_install:
        - virtualenv "${HOME}/GCS_VENV" --python=python3
        - ${HOME}/GCS_VENV/bin/pip install pyopenssl google-cloud-storage absl-py
        - pip install --upgrade virtualenv
        - virtualenv "${HOME}/INSTALL"
      install:
        - travis/install_client_builder.sh
      script:
        - source "${HOME}/INSTALL/bin/activate"
        - travis/build_templates.sh
        - >-
          ${HOME}/GCS_VENV/bin/python
          travis/upload_build_results_to_gcs.py
          --alsologtostderr
          --encrypted_service_key="${PWD}/travis/travis_uploader_service_account.json.enc"
          --build_results_dir="${PWD}/gcs_upload_dir/"

    # OSX builds
    - os: osx
      env:
        - GCS_TAG=osx
      before_install:
        - git clone https://github.com/MacPython/terryfy
        - source terryfy/travis_tools.sh
        - get_python_environment macpython 3.7.3 "${HOME}/GCS_VENV"
        - ${HOME}/GCS_VENV/bin/pip install google-cloud-storage absl-py
        - get_python_environment macpython 2.7.14 "${HOME}/INSTALL"
      install:
        - travis/install_client_builder.sh
      script:
        - source "${HOME}/INSTALL/bin/activate"
        - travis/build_templates.sh
        - >-
          ${HOME}/GCS_VENV/bin/python
          travis/upload_build_results_to_gcs.py
          --alsologtostderr
          --encrypted_service_key="${PWD}/travis/travis_uploader_service_account.json.enc"
          --build_results_dir="${PWD}/gcs_upload_dir/"

    # 64-bit Centos 7 docker container inside an Ubuntu host, for rpm builds
    - os: linux
      dist: xenial
      services:
        - docker
      env:
        - GCS_TAG=centos_64bit
        - DOCKER_IMG=grrdocker/centos7
        - DOCKER_CONTAINER=centos_64bit_container
        - DOCKER_USER=grrbot
      before_install:
        - virtualenv "${HOME}/GCS_VENV" --python=python3
        - ${HOME}/GCS_VENV/bin/pip install google-cloud-storage absl-py
        # Create a Docker container which mounts the GRR repo in the
        # /mnt directory
        - >-
          sudo docker run -dit
          --volume "${PWD}:/mnt/grr"
          --workdir /mnt/grr
          --env DOCKER_USER="${DOCKER_USER}"
          --env TRAVIS_OS_NAME="${TRAVIS_OS_NAME}"
          --name "${DOCKER_CONTAINER}"
          "${DOCKER_IMG}"
        - sudo docker exec "${DOCKER_CONTAINER}" travis/set_up_test_user.sh
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          virtualenv "/home/${DOCKER_USER}/INSTALL"
      install:
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          travis/install_client_builder.sh
      script:
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          travis/build_templates.sh
        # Test installing the built rpm (as root)
        - sudo docker exec "${DOCKER_CONTAINER}" rpm -vih gcs_upload_dir/*.rpm
        - >-
          ${HOME}/GCS_VENV/bin/python
          travis/upload_build_results_to_gcs.py
          --alsologtostderr
          --encrypted_service_key="${PWD}/travis/travis_uploader_service_account.json.enc"
          --build_results_dir="${PWD}/gcs_upload_dir/"

    # Equivalent to the Centos job above, but builds templates that can be
    # installed on Centos 6.
    - os: linux
      dist: xenial
      services:
        - docker
      env:
        - GCS_TAG=centos6_64bit
        - DOCKER_IMG=grrdocker/centos6
        - DOCKER_CONTAINER=centos6_64bit_container
        - DOCKER_USER=grrbot
      before_install:
        - virtualenv "${HOME}/GCS_VENV" --python=python3
        - ${HOME}/GCS_VENV/bin/pip install google-cloud-storage absl-py
        # Create a Docker container which mounts the GRR repo in the
        # /mnt directory
        - >-
          sudo docker run -dit
          --volume "${PWD}:/mnt/grr"
          --workdir /mnt/grr
          --env DOCKER_USER="${DOCKER_USER}"
          --env TRAVIS_OS_NAME="${TRAVIS_OS_NAME}"
          --name "${DOCKER_CONTAINER}"
          "${DOCKER_IMG}"
        - sudo docker exec "${DOCKER_CONTAINER}" travis/set_up_test_user.sh
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          virtualenv "/home/${DOCKER_USER}/INSTALL"
        - >-
          sudo docker exec "${DOCKER_CONTAINER}"
          yum remove -y sqlite-devel || true
      install:
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          travis/install_client_builder.sh
      script:
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          travis/build_templates.sh
        - >-
          ${HOME}/GCS_VENV/bin/python
          travis/upload_build_results_to_gcs.py
          --alsologtostderr
          --encrypted_service_key="${PWD}/travis/travis_uploader_service_account.json.enc"
          --build_results_dir="${PWD}/gcs_upload_dir/"

    # 32-bit Ubuntu docker container inside a 64-bit host, for 32-bit deb builds
    - os: linux
      dist: xenial
      services:
        - docker
      env:
        - GCS_TAG=ubuntu_32bit
        - DOCKER_IMG=grrdocker/ubuntu_i386:xenial
        - DOCKER_CONTAINER=ubuntu_32bit_container
        - DOCKER_USER=grrbot
      before_install:
        - virtualenv "${HOME}/GCS_VENV" --python=python3
        - ${HOME}/GCS_VENV/bin/pip install google-cloud-storage absl-py
        # Create a Docker container which mounts the GRR repo in the
        # /mnt directory
        - >-
          sudo docker run -dit
          --volume "${PWD}:/mnt/grr"
          --workdir /mnt/grr
          --env DOCKER_USER="${DOCKER_USER}"
          --env TRAVIS_OS_NAME="${TRAVIS_OS_NAME}"
          --name "${DOCKER_CONTAINER}"
          "${DOCKER_IMG}"
        - >-
          sudo docker exec "${DOCKER_CONTAINER}"
          linux32 travis/set_up_test_user.sh
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          linux32 virtualenv "/home/${DOCKER_USER}/INSTALL"
      install:
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          linux32 travis/install_client_builder.sh
      script:
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          linux32 travis/build_templates.sh
        - >-
          ${HOME}/GCS_VENV/bin/python
          travis/upload_build_results_to_gcs.py
          --alsologtostderr
          --encrypted_service_key="${PWD}/travis/travis_uploader_service_account.json.enc"
          --build_results_dir="${PWD}/gcs_upload_dir/"

    # 32-bit Centos docker container inside a 64-bit host, for 32-bit rpm builds
    - os: linux
      dist: xenial
      services:
        - docker
      env:
        - GCS_TAG=centos_32bit
        - DOCKER_IMG=grrdocker/centos_i686:7
        - DOCKER_CONTAINER=centos_32bit_container
        - DOCKER_USER=grrbot
      before_install:
        - virtualenv "${HOME}/GCS_VENV" --python=python3
        - ${HOME}/GCS_VENV/bin/pip install google-cloud-storage absl-py
        # Create a Docker container which mounts the GRR repo in the
        # /mnt directory
        - >-
          sudo docker run -dit
          --volume "${PWD}:/mnt/grr"
          --workdir /mnt/grr
          --env DOCKER_USER="${DOCKER_USER}"
          --env TRAVIS_OS_NAME="${TRAVIS_OS_NAME}"
          --name "${DOCKER_CONTAINER}"
          "${DOCKER_IMG}"
        - >-
          sudo docker exec "${DOCKER_CONTAINER}"
          linux32 travis/set_up_test_user.sh
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          linux32 virtualenv "/home/${DOCKER_USER}/INSTALL"
        - >-
          sudo docker exec "${DOCKER_CONTAINER}"
          rm /usr/include/sqlite3.h /usr/include/sqlite3ext.h || true
      install:
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          linux32 travis/install_client_builder.sh
      script:
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          linux32 travis/build_templates.sh
        - >-
          ${HOME}/GCS_VENV/bin/python
          travis/upload_build_results_to_gcs.py
          --alsologtostderr
          --encrypted_service_key="${PWD}/travis/travis_uploader_service_account.json.enc"
          --build_results_dir="${PWD}/gcs_upload_dir/"

    # 64-bit xenial Docker container, for building server debs.
    #
    # Building a server deb in the trusty host did not work out so well -
    # The build would fail with 'error: [Errno 11] Resource temporarily
    # unavailable' after a bunch of file-copy operations. That doesn't happen
    # inside the container.
    - os: linux
      dist: xenial
      services:
        - docker
      env:
        - GCS_TAG=server_deb
        - DOCKER_IMG=ubuntu:xenial
        - DOCKER_CONTAINER=xenial_64bit_container
        - DOCKER_USER=grrbot
      before_install:
        - virtualenv "${HOME}/GCS_VENV" --python=python3
        - ${HOME}/GCS_VENV/bin/pip install google-cloud-storage absl-py
        - >-
          sudo docker run -dit
          --volume "${PWD}:/mnt/grr"
          --workdir /mnt/grr
          --env DOCKER_USER="${DOCKER_USER}"
          --env TRAVIS_OS_NAME="${TRAVIS_OS_NAME}"
          --env TRAVIS_COMMIT="${TRAVIS_COMMIT}"
          --name "${DOCKER_CONTAINER}"
          "${DOCKER_IMG}"
        - >-
          sudo docker exec "${DOCKER_CONTAINER}" apt-get update
        - >-
          sudo docker exec "${DOCKER_CONTAINER}"
          apt-get install -y fakeroot debhelper libffi-dev libssl-dev python-dev
          python-pip wget openjdk-8-jdk zip git devscripts dh-systemd
          libmysqlclient-dev dh-virtualenv dh-make libc6-i386 lib32z1
        - >-
          sudo docker exec "${DOCKER_CONTAINER}"
          pip install --upgrade pip virtualenv
        - sudo docker exec "${DOCKER_CONTAINER}" travis/set_up_test_user.sh
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          virtualenv "/home/${DOCKER_USER}/INSTALL"
      install:
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          travis/install.sh
      script:
        - >-
          travis/fetch_client_templates.sh &&

          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          travis/build_local_pyindex.sh &&

          sudo docker exec "${DOCKER_CONTAINER}"
          travis/build_server_deb.sh
        - >-
          ${HOME}/GCS_VENV/bin/python
          travis/upload_build_results_to_gcs.py
          --alsologtostderr
          --encrypted_service_key="${PWD}/travis/travis_uploader_service_account.json.enc"
          --build_results_dir="${PWD}/gcs_upload_dir/"

cache:
  directories:
    - $HOME/.cache/pip
